@extends('layouts.customer')
@section('title', 'Riwayat Pesanan')
@section('content')
<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-medium text-blue-600 dark:text-blue-400">Aktivitas Anda</p><h1 class="mt-1 text-2xl font-bold">Pesanan Saya</h1><p class="mt-2 text-sm text-slate-500">Semua pesanan dan status terbarunya.</p></div><a href="{{ route('customer.orders.create') }}" class="app-btn app-btn-primary min-h-11 w-full sm:w-auto">+ Pesanan Baru</a></div>
<div class="app-card mt-7 overflow-hidden"><div class="hidden overflow-x-auto md:block"><table class="app-table"><thead><tr><th>Tanggal</th><th>Nomor</th><th>Cabang</th><th>Ukuran / Qty</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>
@forelse($orders as $order)<tr><td>{{ $order->date?->format('d/m/Y') }}</td><td><a class="font-semibold text-blue-600" href="{{ route('customer.orders.show',$order) }}">{{ $order->order_number }}</a></td><td>{{ $order->branch?->name ?? '—' }}</td><td>{{ $order->size ?: '-' }} / {{ number_format($order->qty,0,',','.') }}</td><td><span class="app-badge {{ match($order->status){'completed'=>'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300','cancelled'=>'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300','confirmed','processing'=>'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',default=>'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300'} }}">{{ match($order->status){'pending'=>'Menunggu','confirmed'=>'Dikonfirmasi','processing'=>'Diproses','completed'=>'Selesai','cancelled'=>'Dibatalkan',default=>$order->status} }}</span></td><td class="font-semibold">Rp {{ number_format($order->total,0,',','.') }}</td><td><a class="text-sm font-medium text-blue-600" href="{{ route('customer.orders.show',$order) }}">Detail</a></td></tr>
@empty<tr><td colspan="7"><div class="app-empty"><div class="app-empty-title">Belum ada pesanan</div><div class="app-empty-desc">Pesanan Anda akan muncul di sini.</div><a href="{{ route('customer.orders.create') }}" class="app-btn app-btn-primary mt-2">Buat Pesanan</a></div></td></tr>@endforelse
</tbody></table></div><div class="space-y-3 p-4 md:hidden">@forelse($orders as $order)<article class="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div class="flex items-start justify-between gap-3"><div><a class="font-semibold text-blue-600" href="{{ route('customer.orders.show',$order) }}">{{ $order->order_number }}</a><div class="mt-1 text-xs text-slate-500">{{ $order->date?->format('d/m/Y') }} · {{ $order->branch?->name ?? '—' }}</div></div><span class="app-badge bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300">{{ $order->payment_status === 'paid' ? 'Dibayar' : 'Belum dibayar' }}</span></div><div class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><div class="text-xs text-slate-500">Ukuran / Qty</div><div class="font-medium">{{ $order->size ?: '-' }} / {{ number_format($order->qty,0,',','.') }}</div></div><div><div class="text-xs text-slate-500">Status order</div><div class="mt-1"><span class="app-badge {{ $order->status==='completed'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700' }}">{{ ucfirst($order->status) }}</span></div></div></div><div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 dark:border-slate-800"><b>Rp {{ number_format($order->total,0,',','.') }}</b><a href="{{ route('customer.orders.show',$order) }}" class="app-btn app-btn-secondary min-h-10">Lihat Detail</a></div></article>@empty<div class="app-empty"><div class="app-empty-title">Belum ada pesanan</div><a href="{{ route('customer.orders.create') }}" class="app-btn app-btn-primary mt-2">Buat Pesanan</a></div>@endforelse</div>@if($orders->hasPages())<div class="border-t border-slate-200 p-4 dark:border-slate-800">{{ $orders->links() }}</div>@endif</div>
@endsection
