@extends('layouts.customer') @section('title','Detail Pesanan') @section('content')
@php $payLabels=['unpaid'=>'Belum Dibayar','pending'=>'Menunggu Pembayaran','pending_verification'=>'Menunggu Verifikasi','paid'=>'Sudah Dibayar','failed'=>'Gagal','expired'=>'Kedaluwarsa','rejected'=>'Ditolak','refunded'=>'Dikembalikan']; @endphp
<div class="flex flex-wrap items-center justify-between gap-3"><h1 class="text-2xl font-bold">{{ $order->order_number }}</h1><span class="app-badge {{ $order->payment_status==='paid'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700' }}">{{ $payLabels[$order->payment_status]??$order->payment_status }}</span></div>
<div class="mt-6 grid gap-6 lg:grid-cols-3"><div class="app-card p-6 lg:col-span-2"><div class="grid gap-4 sm:grid-cols-2"><p><b>Cabang:</b> {{ $order->branch->name }}</p><p><b>Metode:</b> {{ $order->payment_method==='payment_gateway'?'Payment Gateway':'Transfer Bank' }}</p><p><b>Ukuran:</b> {{ $order->size }}</p><p><b>Qty:</b> {{ number_format($order->qty,0) }}</p><p><b>Harga satuan:</b> Rp {{ number_format($order->price,0,',','.') }}</p><p><b>Subtotal:</b> Rp {{ number_format($order->subtotal,0,',','.') }}</p><p class="text-lg"><b>Total:</b> Rp {{ number_format($order->total,0,',','.') }}</p><p><b>Status produksi:</b> {{ match($order->status){'waiting_payment'=>'Menunggu pembayaran','pending'=>'Menunggu','confirmed'=>'Dikonfirmasi','processing'=>'Diproses','completed'=>'Selesai','cancelled'=>'Dibatalkan',default=>$order->status} }}</p><div class="sm:col-span-2"><b>Deskripsi:</b><p class="mt-1 whitespace-pre-line">{{ $order->request_text?:'-' }}</p></div>@if($order->design_file_path)<div class="sm:col-span-2"><img src="{{ route('customer.orders.design',[$order,'inline'=>1]) }}" class="max-h-80 rounded-xl border object-contain"><a class="mt-2 inline-block text-blue-600" href="{{ route('customer.orders.design',$order) }}">Unduh desain</a></div>@endif</div></div>
<aside class="app-card p-6"><h2 class="font-semibold">Pembayaran</h2>
@if($order->payment_status==='paid')<div class="mt-4 rounded-xl bg-emerald-100 p-4 text-emerald-800">Pembayaran terkonfirmasi {{ $order->paid_at?->format('d/m/Y H:i') }}.</div>@if($order->customerInvoice)<a class="app-btn app-btn-secondary mt-3 w-full" href="{{ route('customer.invoices.show',$order->customerInvoice) }}">Lihat Invoice</a>@endif
@elseif($order->payment_expired_at?->isPast() || $order->payment_status==='expired')<div class="mt-4 rounded-xl bg-red-100 p-4 text-red-800">Pembayaran kedaluwarsa.</div>
@elseif($order->status==='cancelled')<div class="mt-4 rounded-xl bg-slate-100 p-4 text-slate-700 dark:bg-slate-800 dark:text-slate-200">Pesanan telah dibatalkan dan tidak dapat dibayar.</div>
@elseif($order->payment_method==='payment_gateway')<button id="pay-now" class="app-btn app-btn-primary mt-4 w-full">Bayar Sekarang</button><p class="mt-2 text-xs text-slate-500">Status paid hanya berasal dari webhook Midtrans terverifikasi.</p>
@else
 @if($order->payment_rejection_reason)<div class="mt-4 rounded-xl bg-red-100 p-3 text-red-800">Ditolak: {{ $order->payment_rejection_reason }}</div>@endif
 @forelse($accounts as $account)<div class="mt-4 rounded-xl border p-4"><b>{{ $account->bank_name }}</b><div class="mt-1 flex min-w-0 items-center justify-between gap-3"><code class="min-w-0 break-all">{{ $account->account_number }}</code><button type="button" onclick="navigator.clipboard.writeText('{{ $account->account_number }}')" class="shrink-0 text-xs text-blue-600">Salin</button></div><p>{{ $account->account_holder }}</p><p class="mt-2 text-sm text-slate-500">{{ $account->instructions }}</p></div>@empty<p class="mt-4 text-amber-600">Rekening aktif belum tersedia.</p>@endforelse
 @if($accounts->isNotEmpty() && $order->payment_status!=='pending_verification')<form method="POST" enctype="multipart/form-data" action="{{ route('customer.orders.payment-confirmation',$order) }}" class="mt-5 space-y-3" x-data="{submitting:false}" @submit="if(submitting){$event.preventDefault()}else{submitting=true}">@csrf<select name="payment_account_id" class="app-input" required>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->bank_name }} - {{ $a->account_number }}</option>@endforeach</select><input class="app-input" name="sender_name" placeholder="Nama pengirim" required><input class="app-input" name="sender_bank" placeholder="Bank pengirim" required><input class="app-input" type="date" name="transferred_at" required><input class="app-input" type="number" name="amount" value="{{ (int)$order->total }}" readonly required><input class="app-input" type="file" name="proof" accept="image/jpeg,image/png" required><textarea class="app-input" name="note" placeholder="Catatan"></textarea><button class="app-btn app-btn-primary w-full" :disabled="submitting"><span x-show="!submitting">Upload Bukti</span><span x-show="submitting">Mengunggah...</span></button></form>@endif
@endif</aside></div>
<div class="app-card mt-6 p-6"><h2 class="font-semibold">Timeline</h2><ol class="mt-4 space-y-3 text-sm"><li>✓ Pesanan dibuat</li><li>{{ $order->payment_status==='paid'?'✓':'○' }} Menunggu pembayaran</li><li>{{ $order->payment_status==='paid'?'✓':'○' }} Pembayaran terkonfirmasi</li><li>{{ $order->payment_status==='paid'?'✓':'○' }} Pesanan masuk admin</li><li>{{ in_array($order->status,['processing','completed'])?'✓':'○' }} Diproses</li><li>{{ $order->status==='completed'?'✓':'○' }} Selesai</li></ol></div>
@if($order->status==='awaiting_design_approval' && ($preview=$order->designFiles->firstWhere('kind','admin_preview')))
<section class="app-card mt-6 p-6"><h2 class="font-semibold">Persetujuan desain</h2><p class="mt-2 text-sm text-slate-500">Periksa preview versi {{ $preview->version }} sebelum produksi.</p><a href="{{ route('customer.orders.design-files.download',[$order,$preview]) }}" class="app-btn app-btn-secondary mt-4">Unduh Preview</a><div class="mt-4 grid gap-3 sm:grid-cols-2"><form method="POST" action="{{ route('customer.orders.design-approve',$order) }}">@csrf @method('PATCH')<button class="app-btn app-btn-primary w-full">Setujui Desain</button></form><form method="POST" action="{{ route('customer.orders.design-request-revision',$order) }}" class="space-y-2">@csrf @method('PATCH')<textarea name="comment" class="app-input" required placeholder="Jelaskan revisi yang diminta"></textarea><button class="app-btn app-btn-danger w-full">Minta Revisi</button></form></div></section>
@endif
@if($order->status==='revision_required')
<section class="app-card mt-6 p-6"><h2 class="font-semibold">Upload revisi file</h2><form method="POST" enctype="multipart/form-data" action="{{ route('customer.orders.design-revision',$order) }}" class="mt-4 space-y-3">@csrf<input type="file" name="design_file" accept="image/png" class="app-input" required><textarea name="note" class="app-input" placeholder="Catatan revisi"></textarea><button class="app-btn app-btn-primary">Kirim Revisi</button></form></section>
@endif
<section class="app-card mt-6 p-6"><h2 class="font-semibold">Riwayat status</h2><ol class="mt-4 space-y-3 text-sm">@forelse($order->statusHistories->where('customer_visible',true) as $history)<li><b>{{ str($history->new_status)->replace('_',' ')->title() }}</b> · {{ $history->created_at->format('d/m/Y H:i') }}@if($history->note)<p class="text-slate-500">{{ $history->note }}</p>@endif</li>@empty<li>Pesanan dibuat.</li>@endforelse</ol></section>
@if($order->refunds->isNotEmpty())<section class="app-card mt-6 p-6"><h2 class="font-semibold">Riwayat refund</h2><div class="mt-4 space-y-2 text-sm">@foreach($order->refunds as $refund)<p><b>Rp {{ number_format($refund->amount,0,',','.') }}</b> · {{ $refund->reason }} · {{ $refund->processed_at?->format('d/m/Y H:i') }}</p>@endforeach</div></section>@endif
@endsection
@push('scripts')@if($order->payment_method==='payment_gateway'&&$order->payment_status!=='paid'&&$order->status!=='cancelled'&&!$order->payment_expired_at?->isPast())<script src="{{ config('services.midtrans.is_production')?'https://app.midtrans.com/snap/snap.js':'https://app.sandbox.midtrans.com/snap/snap.js' }}" data-client-key="{{ config('services.midtrans.client_key') }}"></script><script>document.getElementById('pay-now')?.addEventListener('click',async()=>{const button=document.getElementById('pay-now');button.disabled=true;button.textContent='Memproses...';try{const r=await fetch(@json(route('customer.orders.snap',$order)),{method:'POST',headers:{'X-CSRF-TOKEN':@json(csrf_token()),'Accept':'application/json'}});const d=await r.json();if(!r.ok){throw new Error(d.message||'Gagal membuat pembayaran')}window.snap.pay(d.token,{onSuccess:()=>location.reload(),onPending:()=>location.reload(),onError:()=>location.reload(),onClose:()=>{button.disabled=false;button.textContent='Bayar Sekarang'}})}catch(e){window.showErrorAlert?showErrorAlert('Pembayaran gagal',e.message):console.error(e);button.disabled=false;button.textContent='Bayar Sekarang'}});</script>@endif @endpush
