@extends('layouts.customer')
@section('title', 'Dashboard')
@section('content')
<div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end">
    <div><p class="text-sm font-medium text-blue-600 dark:text-blue-400">Dashboard customer</p><h1 class="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Halo, {{ auth()->user()->name }}</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Pantau proses pesanan dan pembayaran Anda dari sini.</p></div>
    <a href="{{ route('customer.orders.create') }}" class="app-btn app-btn-primary min-h-11 w-full sm:w-auto">+ Buat Pesanan</a>
</div>
<div class="mt-7 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
    @foreach([['Total pesanan',$totalOrders,'text-blue-600','bg-blue-50 dark:bg-blue-900/30'],['Menunggu',$pendingOrders,'text-amber-600','bg-amber-50 dark:bg-amber-900/30'],['Diproses',$processingOrders,'text-indigo-600','bg-indigo-50 dark:bg-indigo-900/30'],['Selesai',$completedOrders,'text-emerald-600','bg-emerald-50 dark:bg-emerald-900/30']] as [$label,$value,$color,$iconBg])
    <div class="app-stat-card flex items-center justify-between"><div><div class="text-sm text-slate-500 dark:text-slate-400">{{ $label }}</div><div class="mt-2 text-3xl font-bold {{ $color }}">{{ $value }}</div></div><div class="rounded-2xl p-3 {{ $iconBg }}"><span class="text-xl font-bold {{ $color }}">{{ $label === 'Total pesanan' ? '#' : ($label === 'Selesai' ? '✓' : '•') }}</span></div></div>
    @endforeach
</div>
<div class="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(18rem,0.75fr)]">
<section class="app-card overflow-hidden"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><div><h2 class="font-semibold">Pesanan terbaru</h2><p class="mt-1 text-xs text-slate-500">Order yang sedang berjalan</p></div><a href="{{ route('customer.orders.index') }}" class="text-sm font-medium text-blue-600 hover:text-blue-700">Lihat semua</a></div>
<div class="hidden overflow-x-auto md:block"><table class="app-table"><thead><tr><th>Nomor</th><th>Cabang</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>
@forelse($recentOrders as $order)<tr><td class="font-semibold">{{ $order->order_number }}</td><td>{{ $order->branch?->name ?? '—' }}</td><td><span class="app-badge {{ $order->status==='completed'?'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300':'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300' }}">{{ ucfirst($order->status) }}</span></td><td class="font-semibold">Rp {{ number_format($order->total,0,',','.') }}</td><td><a class="text-sm font-medium text-blue-600" href="{{ route('customer.orders.show',$order) }}">Detail</a></td></tr>
@empty<tr><td colspan="5"><div class="app-empty"><div class="app-empty-title">Belum ada pesanan</div><div class="app-empty-desc">Buat pesanan custom pertama Anda.</div><a href="{{ route('customer.orders.create') }}" class="app-btn app-btn-primary mt-2">Buat Pesanan</a></div></td></tr>@endforelse
</tbody></table></div>
<div class="space-y-3 p-4 md:hidden">@forelse($recentOrders as $order)<a href="{{ route('customer.orders.show',$order) }}" class="block rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div class="flex items-start justify-between gap-3"><div><div class="font-semibold">{{ $order->order_number }}</div><div class="mt-1 text-sm text-slate-500">{{ $order->branch?->name ?? '—' }}</div></div><span class="app-badge {{ $order->status==='completed'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700' }}">{{ ucfirst($order->status) }}</span></div><div class="mt-4 font-semibold">Rp {{ number_format($order->total,0,',','.') }}</div></a>@empty<div class="app-empty"><div class="app-empty-title">Belum ada pesanan</div><a href="{{ route('customer.orders.create') }}" class="app-btn app-btn-primary mt-2">Buat Pesanan</a></div>@endforelse</div></section>
<section class="app-card"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 class="font-semibold">Notifikasi terbaru</h2><p class="mt-1 text-xs text-slate-500">Informasi pesanan dan pembayaran</p></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($latestNotifications as $notification)<a href="{{ route('notifications.visit',$notification->id) }}" class="block px-5 py-4 hover:bg-slate-50 dark:hover:bg-slate-800/60"><div class="flex gap-3"><span class="mt-1 h-2 w-2 shrink-0 rounded-full {{ $notification->read_at ? 'bg-slate-300' : 'bg-blue-600' }}"></span><div class="min-w-0"><div class="truncate text-sm font-medium">{{ $notification->data['title'] ?? 'Notifikasi' }}</div><div class="mt-1 line-clamp-2 text-xs text-slate-500">{{ $notification->data['message'] ?? '' }}</div><div class="mt-2 text-[11px] text-slate-400">{{ $notification->created_at?->diffForHumans() }}</div></div></div></a>@empty<div class="app-empty"><div class="app-empty-title">Belum ada notifikasi</div><div class="app-empty-desc">Kami akan memberi tahu perkembangan pesanan Anda.</div></div>@endforelse</div></section>
</div>
@endsection
