@extends('layouts.app')
@section('title','Pesanan Customer')
@section('content')
<div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p class="text-sm text-slate-500">Pesanan customer</p><h1 class="mt-1 text-2xl font-bold">{{ $order->order_number }}</h1><p class="mt-1 text-sm text-slate-500">{{ $order->user?->name ?? 'Customer' }} · {{ $order->user?->whatsapp ?? '—' }}</p></div><span class="app-badge bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300">{{ $order->branch?->name ?? '—' }}</span></div>
<div class="mt-6 grid gap-6 lg:grid-cols-3"><section class="app-card p-5 sm:p-6 lg:col-span-2"><h2 class="font-semibold">Detail desain</h2><div class="mt-5 grid gap-5 text-sm sm:grid-cols-2"><div class="sm:col-span-2"><span class="text-xs text-slate-500">Deskripsi</span><p class="mt-1 whitespace-pre-line">{{ $order->request_text ?: 'Tidak ada deskripsi.' }}</p></div><div><span class="text-xs text-slate-500">Ukuran</span><p class="mt-1 font-medium">{{ $order->size ?: '—' }}</p></div><div><span class="text-xs text-slate-500">Jumlah</span><p class="mt-1 font-medium">{{ number_format($order->qty,0) }} item</p></div><div class="sm:col-span-2"><span class="text-xs text-slate-500">Catatan customer</span><p class="mt-1 whitespace-pre-line">{{ $order->note ?: '—' }}</p></div>@if($order->design_file_path)<div class="sm:col-span-2"><a class="app-btn app-btn-secondary min-h-11 w-full sm:w-auto" href="{{ route('orders.design',$order) }}">Unduh PNG secara aman</a></div>@endif</div></section><aside class="app-card h-fit p-5 sm:p-6"><h2 class="font-semibold">Perbarui status</h2><form method="POST" action="{{ route('orders.customer-status',$order) }}" class="mt-5 space-y-4">@csrf @method('PATCH')<label class="block text-sm font-medium">Status produksi<select name="status" class="app-input mt-2 min-h-11 text-base">@foreach(['file_review'=>'Pemeriksaan File','revision_required'=>'Perlu Revisi','awaiting_design_approval'=>'Menunggu Approval','production_queue'=>'Antrean Produksi','printing'=>'Sedang Dicetak','quality_control'=>'Quality Control','ready_pickup'=>'Siap Diambil','shipped'=>'Dikirim','completed'=>'Selesai','cancelled'=>'Dibatalkan'] as $key=>$label)<option value="{{ $key }}" @selected($order->status===$key)>{{ $label }}</option>@endforeach</select></label><label class="block text-sm font-medium">Estimasi selesai<input type="datetime-local" name="estimated_completion_at" class="app-input mt-2" value="{{ $order->estimated_completion_at?->format('Y-m-d\\TH:i') }}"></label><label class="block text-sm font-medium">Catatan untuk customer<textarea name="customer_note" class="app-input mt-2 text-base" rows="3">{{ $order->customer_note }}</textarea></label><label class="block text-sm font-medium">Catatan internal<textarea name="internal_note" class="app-input mt-2 text-base" rows="3">{{ $order->internal_note }}</textarea></label><button class="app-btn app-btn-primary min-h-11 w-full">Simpan Perubahan</button></form></aside></div>
@if($order->payment_status==='paid' && in_array($order->status,['file_review','revision_required']))
<section class="app-card mt-6 p-5 sm:p-6"><h2 class="font-semibold">Upload preview desain</h2><form method="POST" enctype="multipart/form-data" action="{{ route('orders.design-preview',$order) }}" class="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]">@csrf<input type="file" name="preview" accept="image/png" class="app-input" required><input name="note" class="app-input" placeholder="Catatan untuk customer"><button class="app-btn app-btn-primary">Kirim Preview</button></form></section>
@endif
<section class="app-card mt-6 p-5 sm:p-6"><h2 class="font-semibold">Riwayat file dan status</h2><div class="mt-4 flex flex-wrap gap-2">@foreach($order->designFiles as $file)<a class="app-btn app-btn-secondary" href="{{ route('orders.design-files.download',[$order,$file]) }}">{{ str($file->kind)->replace('_',' ')->title() }} v{{ $file->version }}</a>@endforeach</div><ol class="mt-5 space-y-2 text-sm">@foreach($order->statusHistories as $history)<li>{{ str($history->new_status)->replace('_',' ')->title() }} · {{ $history->created_at->format('d/m/Y H:i') }}</li>@endforeach</ol></section>
@if(auth()->user()->hasAnyRole(['Super Admin','Owner','Finance']) && in_array($order->payment_status,['paid','refunded']))
<section class="app-card mt-6 p-5 sm:p-6"><h2 class="font-semibold">Refund pembayaran</h2><div class="mt-4 space-y-2 text-sm">@forelse($order->refunds as $refund)<p><b>Rp {{ number_format($refund->amount,0,',','.') }}</b> · {{ $refund->reason }} · {{ $refund->processed_at?->format('d/m/Y H:i') }}</p>@empty<p class="text-slate-500">Belum ada refund.</p>@endforelse</div>@if($order->payment_status==='paid')<form method="POST" action="{{ route('orders.refunds.store',$order) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<input class="app-input" type="number" min="1" max="{{ (int)($order->total-$order->refunds->where('status','completed')->sum('amount')) }}" name="amount" placeholder="Nominal refund" required><input class="app-input" name="provider_reference" placeholder="Referensi provider/bank (opsional)"><textarea class="app-input sm:col-span-2" name="reason" placeholder="Alasan refund" required></textarea><label class="flex items-start gap-2 text-sm sm:col-span-2"><input class="mt-1" type="checkbox" name="confirmed" value="1" required><span>Saya memastikan refund sudah benar-benar diproses di gateway atau rekening bank. Form ini hanya mencatat transaksi, bukan mengirim dana.</span></label><button class="app-btn app-btn-danger sm:col-span-2">Catat Refund</button></form>@endif</section>
@endif
@endsection
