@extends('layouts.app')

@section('title', 'Closing Mingguan')

@section('content')
    <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-bold tracking-tight text-[#0F172A] dark:text-[#F8FAFC]">Closing Mingguan</h1><p class="mt-1 text-sm text-[#64748B] dark:text-[#94A3B8]">Pencocokan pesanan sistem per customer; tidak mencampurkan HPP atau pengeluaran.</p></div><a href="{{ route('orders.daily-summary', ['branch_id' => $branchId]) }}" class="rounded-xl border border-[#E2E8F0] bg-white px-4 py-2 text-sm font-semibold text-[#0F172A] shadow-sm dark:border-[#253247] dark:bg-[#111827] dark:text-[#F8FAFC]">Sum Harian</a></div>
    <form class="mt-5 flex flex-wrap items-end gap-3 rounded-2xl border border-[#E2E8F0] bg-white p-4 shadow-sm dark:border-[#253247] dark:bg-[#111827]"><input type="hidden" name="branch_id" value="{{ $branchId }}"><div><label class="mb-1 block text-xs font-semibold uppercase tracking-wide text-[#64748B]">Tanggal Mulai</label><input type="date" name="start_date" value="{{ $startDate }}" class="rounded-xl border border-[#E2E8F0] bg-white px-3 py-2 text-sm dark:border-[#253247] dark:bg-[#0B1220] dark:text-[#F8FAFC]"></div><div><label class="mb-1 block text-xs font-semibold uppercase tracking-wide text-[#64748B]">Tanggal Akhir</label><input type="date" name="end_date" value="{{ $endDate }}" class="rounded-xl border border-[#E2E8F0] bg-white px-3 py-2 text-sm dark:border-[#253247] dark:bg-[#0B1220] dark:text-[#F8FAFC]"></div><button class="rounded-xl bg-[#2563EB] px-4 py-2 text-sm font-semibold text-white hover:bg-[#1D4ED8]">Tampilkan Closing</button></form>
    <div class="mt-5 space-y-5">
        @forelse($rows as $customerRows)
            @php($customerTotal = $customerRows->sum('total'))
            <section class="overflow-hidden rounded-2xl border border-[#E2E8F0] bg-white shadow-sm dark:border-[#253247] dark:bg-[#111827]"><div class="flex items-center justify-between border-b border-[#E2E8F0] px-5 py-4 dark:border-[#253247]"><h2 class="font-bold text-[#0F172A] dark:text-[#F8FAFC]">{{ $customerRows->first()->customer_name }}</h2><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700 dark:bg-blue-500/10 dark:text-blue-400">Total Sistem</span></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-[#F8FAFC] text-left dark:bg-[#0B1220]"><tr><th class="p-4 text-[#64748B]">Tanggal</th><th class="p-4 text-right text-[#64748B]">Jumlah Qty</th><th class="p-4 text-right text-[#64748B]">Total Pesanan</th></tr></thead><tbody>@foreach($customerRows as $row)<tr class="border-t border-[#E2E8F0] dark:border-[#253247]"><td class="p-4 text-[#0F172A] dark:text-[#F8FAFC]">{{ \Carbon\Carbon::parse($row->date)->translatedFormat('d F Y') }}</td><td class="p-4 text-right text-[#64748B]">{{ number_format($row->total_qty, 2, ',', '.') }}</td><td class="p-4 text-right font-semibold text-[#0F172A] dark:text-[#F8FAFC]">Rp {{ number_format($row->total, 0, ',', '.') }}</td></tr>@endforeach</tbody><tfoot class="border-t-2 border-[#0F172A] dark:border-[#F8FAFC]"><tr><td class="p-4 font-bold text-[#0F172A] dark:text-[#F8FAFC]">Total {{ $customerRows->first()->customer_name }}</td><td class="p-4 text-right font-bold text-[#2563EB]">{{ number_format($customerRows->sum('total_qty'), 2, ',', '.') }}</td><td class="p-4 text-right font-bold text-[#2563EB]">Rp {{ number_format($customerTotal, 0, ',', '.') }}</td></tr></tfoot></table></div></section>
        @empty
            <div class="rounded-2xl border border-[#E2E8F0] bg-white p-10 text-center text-[#94A3B8] shadow-sm dark:border-[#253247] dark:bg-[#111827]">Tidak ada pesanan aktif pada rentang tanggal ini.</div>
        @endforelse
    </div>
@endsection
